# Generated by Django 4.1.7 on 2023-03-18 15:01

import ckeditor.fields
from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField()),
                ('choices', models.TextField()),
                ('answer', models.TextField()),
                ('explanation', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('explanation_type', models.CharField(blank=True, choices=[('text', 'Teks'), ('youtube', 'Youtube')], default=None, max_length=20, null=True)),
                ('type', models.CharField(choices=[('pilihan-ganda', 'Pilihan Ganda'), ('tabel-benar-salah', 'Tabel Benar Salah')], default='pilihan-ganda', max_length=20)),
                ('subject', models.CharField(blank=True, choices=[('penalaran-matematika', 'Penalaran Matematika'), ('pengetahuan-kuantitatif', 'Pengetahuan Kuantitatif')], db_index=True, default=None, max_length=100, null=True)),
                ('source', models.CharField(choices=[('snbt', 'SNBT'), ('utbk', 'UTBK')], db_index=True, default='snbt', max_length=10)),
                ('year', models.CharField(db_index=True, max_length=4, validators=[quiz.models.validate_year])),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
